---
apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  namespace: sock-shop
  labels:
    app: grafana
    component: core
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  selector:
    app: grafana
    component: core